package com.quesmarkt.usermanagementservice.data.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.quesmarkt.usermanagementservice.data.converter.ZonedDateTypeConverter;
import lombok.Data;

import java.time.ZonedDateTime;

/**
 * @author anercan
 */

@Data
@DynamoDBTable(tableName = "loginTransaction")
public class LoginTransaction {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "date")
    @DynamoDBTypeConverted(converter = ZonedDateTypeConverter.class)
    private ZonedDateTime date;

    @DynamoDBAttribute(attributeName = "ip")
    private String ip;

    @DynamoDBAttribute(attributeName = "zone")
    private String zone;

    @DynamoDBAttribute(attributeName = "appId")
    private Integer appId;

    @DynamoDBAttribute(attributeName = "isLoginSucceed")
    private boolean loginSucceed;


}
