package com.quesmarkt.usermanagementservice.data.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.quesmarkt.usermanagementservice.data.converter.ZonedDateTypeConverter;
import com.quesmarkt.usermanagementservice.data.enums.UserState;
import lombok.Data;

import java.time.ZonedDateTime;

/**
 * @author anercan
 */

@Data
@DynamoDBTable(tableName = "users")
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "username")
    private String username;

    @DynamoDBAttribute(attributeName = "password")
    private String password;

    @DynamoDBAttribute(attributeName = "createdDate")
    @DynamoDBTypeConverted(converter = ZonedDateTypeConverter.class)
    private ZonedDateTime createdDate;

    @DynamoDBAttribute(attributeName = "avatarUrl")
    private String avatarUrl;

    @DynamoDBAttribute(attributeName = "appId")
    private Integer appId;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "state")
    private UserState state;

    @DynamoDBAttribute(attributeName = "zone")
    private String zone;

    @DynamoDBAttribute(attributeName = "premiumInfo")
    private PremiumInfo premiumInfo;
}
