package com.quizmarkt.usermanagementservice.data.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

/**
 * @author anercan
 */

@Data
@DynamoDBTable(tableName = "app_config")
public class AppConfig {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "packageName")
    private String packageName;

    @DynamoDBAttribute(attributeName = "name")
    private String appName;

    @DynamoDBAttribute(attributeName = "googlePlayConfigJson")
    private String googlePlayConfigJson;

    @DynamoDBAttribute(attributeName = "appId")
    private Integer appId;

    @DynamoDBAttribute(attributeName = "googleAuthClientUrl")
    private String googleAuthClientUrl;

}
