package com.quizmarkt.usermanagementservice.data.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

/**
 * @author anercan
 */

@Data
@DynamoDBTable(tableName = "subscription_transactions")
public class SubscriptionTransaction {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "googleSubscriptionRequest")
    private GoogleSubscriptionRequest googleSubscriptionRequest;

    @DynamoDBAttribute(attributeName = "googleSubscriptionPurchaseResponse")
    private GoogleSubscriptionPurchaseResponse googleSubscriptionPurchaseResponse;

    @DynamoDBAttribute(attributeName = "appId")
    private Integer appId;

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;
}
